### ISSUE TITLE
-webkit-line-clamp has pixel value instead of unit value

### ISSUE THREAD

**Issue by lukebennett88** [tailwindlabs/tailwindcss-line-clamp#2]
I just tried adding this plugin to a project. I was replacing an existing plugin with the same API (https://github.com/JamesHRowe/tailwindcss-line-clamp/blob/master/index.js).

However the outputted CSS looks like this with the new plugin:

```css
.line-clamp-3 {
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3px;
}
```

![image](https://user-images.githubusercontent.com/3422401/103843483-01584c80-50ec-11eb-9329-af66ed8f7552.png)

I just had a look at the source of both hoping I could figure it out and submit a PR, but from what I can tell, they both look pretty similar and I can't see why `px`  would be getting appended to the value.

Hopefully it's something simple!
